[package]
name = "classicl_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
classicl = { git = "https://gitlab.com/nokoe/classicl" }
tokio = { version = "1.20.0", features = ["full"] }
libflate = "1.2.0"
noise = "0.7.0"